version: "3.3"
services:
  app:
    image: soladi/soladi:27
    restart: always
    environment:
      SECRET_KEY_BASE: "some-secret"
      DB_URL: "postgresql://postgres:postgres@db:5432/soladi"
      RAILS_SERVE_STATIC_FILES: "true"
    ports:
      - 3000:3000

  db:
    image: library/postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: soladi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
