version: "3.3"
services:
  app:
    image: soladi/soladi:20
    restart: always
    environment:
      SECRET_KEY_BASE: "some-secret"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
    ports:
      - 3000:3000

  db:
    image: library/postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: soladi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
