version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - docker-hub

jobs:
  build:
    docker:
      - image: docker:20.10.2-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build application Docker image
          command: |
            docker build -t soladi/soladi:$CIRCLE_BUILD_NUM .
            docker tag soladi/soladi:$CIRCLE_BUILD_NUM soladi/soladi:latest
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push soladi/soladi:$CIRCLE_BUILD_NUM
          docker push soladi/soladi:latest
