version: "3.3"
services:
  db:
    image: library/postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: soladi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
